# Generated by Django 4.2.1 on 2024-06-11 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Номер телефона должен содержать от 9 до 15 цифр.', regex='^\\d{9,15}$')]),
        ),
    ]
